Theme Submission: hugo-eureka
stackbithq/jamstackthemes pull request #161
Opened 2020-11-22 08:10 UTC by wangchucheng

2020-11-30 01:57 UTC, JugglerX requested changes
@wangchucheng thank you for you submission, just a few minor things to update and I can merge it, thanks!

2020-11-30 01:57 UTC, JugglerX commented on content/theme/hugo-eureka.md
> +  - Tailwindcss
This should be `Tailwind`

2020-11-30 01:57 UTC, JugglerX commented on content/theme/hugo-eureka.md
> +date: 2020-11-22 # Enter the date you submitted the theme YYYY-MM-DD
Please remove comments from front-matter

2020-11-30 01:57 UTC, JugglerX commented on content/theme/hugo-eureka.md
> +  - Posts
This isn't the specific Hugo archetypes, its more the type of website. You can use `Documentation` and `Blog` here

2020-11-30 04:26 UTC, wangchucheng commented
@JugglerX Hi, I have made some changes to fix those. If there are still some problems, please don't hesitate to tell me. Thank you for your time!

2020-12-04 00:27 UTC, JugglerX approved these changes

2020-12-04 00:27 UTC, merged